#
# Theme setup
#
# If you use go mod to install your theme, you must use the URL of the theme.
# If your theme is in the themes directory, you just need to specify its name.
#
baseURL = "https://yonmilk.gitlab.io/portfolio/"
title = "YONMILK"
description = "Personal blog sharing thoughts, experiences, and discoveries"
theme = ["github.com/adityatelange/hugo-PaperMod"]
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[pagination]
pagerSize = 5

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = ["posts", "papermod"]

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.en.menu.main]]
name = "PROJECTS"
url = "/projects/"
weight = 1
[[languages.en.menu.main]]
name = "ACTIVITIES"
url = "/activities/"
weight = 2
[[languages.en.menu.main]]
name = "PROFILE"
url = "/profile/"
weight = 3

[languages.ko]
languageName = "한국어"
weight = 2
title = "YONMILK"

[languages.ko.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.ko.menu.main]]
name = "프로젝트"
url = "/projects/"
weight = 1
[[languages.ko.menu.main]]
name = "활동"
url = "/activities/"
weight = 2
[[languages.ko.menu.main]]
name = "프로필"
url = "/profile/"
weight = 3

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
description = "Personal blog sharing thoughts, experiences, and discoveries"
author = "YONMILK"
defaultTheme = "light"
disableThemeToggle = true
ShowShareButtons = false
ShowReadingTime = false
displayFullLangName = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowRssButtonInSectionTermList = false
ShowAllPagesInArchive = false
ShowPageNums = false
ShowToc = false

[params.profileMode]
enabled = false

[[params.socialIcons]]
name = "github"
title = "View Source on Github"
url = "https://github.com/yonmilk"

[params.assets]
disableHLJS = true

[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
